"""
Combined Gantt figure for flexible T scenarios (beamer-ready).
Top-left : baseline (normal) schedule
Other panels: SPOC optimal solutions

Schedules and costs are read from the JSON report generated by run_crashing_fix.py.
"""
import json
import math
import argparse
from pathlib import Path
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.lines import Line2D

def main():
    parser = argparse.ArgumentParser(description="Generate combined Gantt chart for a specific deadline T.")
    parser.add_argument('--T', type=int, default=246, help="Deadline T (e.g., 241, 246)")
    args = parser.parse_args()
    
    T_DEADLINE = args.T

    current_dir = Path(__file__).resolve().parent
    DATA = current_dir.parent
    
    # Check if report exists
    report_path = DATA / "outputs_azarya" / "sweep" / f"report_ilp_vs_spoc_T{T_DEADLINE}.json"
    if not report_path.exists():
        print(f"Error: JSON report not found at {report_path}")
        print(f"Please generate it first by running run_crashing_fix.py for T={T_DEADLINE}")
        return

    print(f"Loading report from {report_path}")
    with open(report_path, "r", encoding="utf-8") as f:
        report = json.load(f)

    # ---------------------------------------------------------------- get data
    # Normal Baseline is just tasks without any crashing
    # We can reconstruct it from the first solution's normal durations, but we need start times.
    # To get start times for normal, we can just run the schedule function, OR we can notice that
    # if we have no crash, we just do a forward pass. Since we have the problem data:
    acts = json.load(open(DATA / 'activity_data_v3.json'))
    cap  = json.load(open(DATA / 'resource_capacity_v3.json'))
    req  = json.load(open(DATA / 'resource_requirements_v3.json'))
    names = list(acts.keys())
    
    def schedule(durations):
        horizon = sum(durations.values()) + 10
        usage = {r: [0] * horizon for r in cap}
        start, finish = {}, {}
        order, remaining = [], set(names)
        while remaining:
            for n in names:
                if n in remaining and all(p in order for p in acts[n]['required_activities']):
                    order.append(n)
                    remaining.discard(n)
        for n in order:
            d = durations[n]
            t = max([finish[p] for p in acts[n]['required_activities']], default=0)
            while True:
                ok = all(
                    usage[r][day] + a <= cap[r]
                    for r, a in req[n].items() if a
                    for day in range(t, t + d)
                )
                if ok:
                    break
                t += 1
            start[n], finish[n] = t, t + d
            for r, a in req[n].items():
                if a:
                    for day in range(t, t + d):
                        usage[r][day] += a
        return start, finish

    normal_dur = {n: acts[n]['activity_normal_time'] for n in names}
    base_start, base_finish = schedule(normal_dur)
    base_ms = max(base_finish.values())

    y_order = sorted(names, key=lambda n: (base_start[n], names.index(n)))
    y_pos = {n: len(y_order) - 1 - i for i, n in enumerate(y_order)}

    panels = [('Baseline (Normal Schedule)', base_start, normal_dur, [], base_ms, None)]
    
    spoc_sols = report.get("spoc_solutions", [])
    for idx, sol in enumerate(spoc_sols):
        dur = {}
        s = {}
        crashed = []
        for task in sol["tasks"]:
            n = task["task_name"]
            dur[n] = task["duration"]
            s[n] = task["start"]
            if task["crash_days"] > 0:
                crashed.append(n)
        
        # Adjust label to be shorter if there are many solutions
        label = f'SPOC Optimal Sol {idx+1} of {len(spoc_sols)}'
        ms = sol["makespan"]
        z = sol["total_crash_cost"]
        panels.append((label, s, dur, crashed, ms, z))

    # ---------------------------------------------------------------- plot
    plt.rcParams.update({'font.size': 11})
    
    num_panels = len(panels)
    cols = 2
    rows = math.ceil(num_panels / cols)
    
    # Adjust height based on rows (original 2x2 was 11.5)
    fig_height = 11.5 * (rows / 2.0)
    fig, axes = plt.subplots(rows, cols, figsize=(15.5, fig_height), sharex=True, sharey=True)
    
    # Ensure axes is a 1D array for easier iteration, even if it's 1x2 or bigger
    if rows == 1:
        axes_flat = axes
    else:
        axes_flat = axes.flat

    BLUE, RED = '#3B8FD4', '#D64541'

    for i, ax in enumerate(axes_flat):
        if i >= num_panels:
            ax.set_visible(False)
            continue
            
        label, s, dur, crashed, ms, z = panels[i]
        
        for n in names:
            is_crashed = n in crashed
            ax.barh(y_pos[n], dur[n], left=s[n], height=0.62,
                    color=RED if is_crashed else BLUE, edgecolor='black', linewidth=0.5)
            d = dur[n]
            if d >= 4:
                ax.text(s[n] + d / 2, y_pos[n], str(d), ha='center', va='center',
                        color='white', fontsize=7.5, fontweight='bold')
            else:
                ax.text(s[n] + d + 1.5, y_pos[n], str(d), ha='left', va='center',
                        fontsize=7.5)
                        
        if z is not None:
            ax.axvline(T_DEADLINE, color='red', linestyle='--', linewidth=1.6)
            ax.set_title(f'{label}\nmakespan {ms}, crash cost $Z^*$ = {z:.0f}',
                         fontsize=12.5)
        else:
            ax.set_title(f'{label}\nmakespan {ms} (no crashing)', fontsize=12.5)
            
        ax.set_xlim(0, 262)
        ax.set_ylim(-0.8, len(names) - 0.2)
        ax.grid(axis='x', linestyle=':', alpha=0.5)
        ax.tick_params(axis='y', labelsize=9)

    # Set ylabels only for the first column
    if rows > 1:
        for r in range(rows):
            axes[r, 0].set_yticks([y_pos[n] for n in y_order])
            axes[r, 0].set_yticklabels(y_order)
            
        # Set xlabels only for the bottom visible row in each column
        for c in range(cols):
            bottom_row = rows - 1
            while bottom_row >= 0 and not axes[bottom_row, c].get_visible():
                bottom_row -= 1
            if bottom_row >= 0:
                axes[bottom_row, c].set_xlabel('Project Day', fontsize=12)
    else:
        axes[0].set_yticks([y_pos[n] for n in y_order])
        axes[0].set_yticklabels(y_order)
        axes[0].set_xlabel('Project Day', fontsize=12)
        axes[1].set_xlabel('Project Day', fontsize=12)

    fig.suptitle(f'Project Crashing via SPOC — RCPSP–TCT (n = 25, T = {T_DEADLINE})',
                 fontsize=16, y=1.0 - (0.015 / (rows/2.0)))
                 
    handles = [
        mpatches.Patch(facecolor=BLUE, edgecolor='black', label='Normal (no crash)'),
        mpatches.Patch(facecolor=RED, edgecolor='black', label='Crashed (duration < normal)'),
        Line2D([0], [0], color='red', linestyle='--', linewidth=1.6,
               label=f'Deadline T = {T_DEADLINE}'),
    ]
    
    # Adjust legend position slightly depending on height
    fig.legend(handles=handles, loc='lower center', ncol=3, fontsize=11.5,
               frameon=True, bbox_to_anchor=(0.5, 0.0))
               
    # Adjust bottom margin based on rows
    bottom_margin = 0.035 * (2.0 / rows)
    fig.tight_layout(rect=[0, bottom_margin, 1, 1.0 - (0.035 / (rows/2.0))])

    out = current_dir / "figure"
    out.mkdir(parents=True, exist_ok=True)
    
    png_path = out / f'gantt_combined_T{T_DEADLINE}.png'
    pdf_path = out / f'gantt_combined_T{T_DEADLINE}.pdf'
    
    fig.savefig(png_path, dpi=300, bbox_inches='tight')
    fig.savefig(pdf_path, bbox_inches='tight')
    print(f'Saved to {png_path}')

if __name__ == "__main__":
    main()
